Deneme/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Deneme.Models
{
    public class Context : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=LAPTOPSN-PF22HQ\\DENEME;database=IndataLink2;integrated security=true");
        }
        public DbSet<Link> Links { get; set; }

    }
}

Deneme/Models/Link.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Deneme.Models
{
    public class Link
    {
        public int Id { get; set; }
        public string LongUrl { get; set; }

        public string Code { get; set; }
        public string ShortUrl { get; set; }
    }
}

Deneme/Controllers/HomeController.cs
using Deneme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Deneme.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
           
            return View();
        }
        public void RedirectLink()
        {
            using (Context context = new Context())
            {
                string url = Request["aspxerrorpath"]?.Replace("/", "");
                string longUrl = context.Links.Where(x => x.Code == url).Select(s => s.LongUrl).FirstOrDefault().ToString();
                Console.WriteLine(longUrl);
                Response.RedirectPermanent(longUrl, true);
            }
            
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Deneme/Controllers/UrlController.cs
using Deneme.Models;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Deneme.Controllers
{
    public class UrlController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {

            var deger = c.Links.ToList();
            return View(deger);
        }
        [HttpPost]
        public ActionResult Index(Link p)
        {

            Random random = new Random();
            string[] karakter = { "A", "B", "C", "D" };
            int k1, k2, k3, s1, s2, s3;

            k1 = random.Next(0, 4);
            k2 = random.Next(0, 4);
            k3 = random.Next(0, 4);
            s1 = random.Next(0, 9);
            s2 = random.Next(0, 9);
            s3 = random.Next(0, 9);

            string kod = s1.ToString() + karakter[k1] + s2.ToString() + karakter[k2] + s3.ToString() + karakter[k3];
            p.ShortUrl = "https://localhost:44380/" + kod;
            p.Code = kod;
            c.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult QRCode()
        {
            return View();

        }
        [HttpPost]
        public ActionResult QRCode(int id)
        {
            var deger = c.Links.Where(x => x.Id == id).Select(s => s.ShortUrl).FirstOrDefault();
            ViewBag.d = deger;

            using (MemoryStream ms = new MemoryStream())
            {
                QRCodeGenerator koduret = new QRCodeGenerator();
                QRCodeGenerator.QRCode karekod = koduret.CreateQrCode(deger, QRCodeGenerator.ECCLevel.Q);
                using (Bitmap resim = karekod.GetGraphic(10))
                {
                    resim.Save(ms, ImageFormat.Png);
                    ViewBag.karekodImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();
            
        }



    }
}

Deneme/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Deneme/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Deneme/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Deneme/Views/Shared/UrlLayout.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Indata Link</title>

    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
    
    <!-- Template CSS -->
    <link rel="stylesheet" href="~/web/assets/css/style-starter.css">
  </head>
  <body>
<!-- header -->
<header id="site-header" class="fixed-top">
  <div class="container">
      <nav class="navbar navbar-expand-lg stroke">
          <a class="navbar-brand" href="/Url/Index">
              <span class="fa fa-cube"></span> Indata Link
          </a>
          <!-- if logo is image enable this   
      <a class="navbar-brand" href="#index.html">
          <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
      </a> -->
          <button class="navbar-toggler  collapsed bg-gradient" type="button" data-toggle="collapse"
              data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
              <span class="navbar-toggler-icon fa icon-close fa-times"></span>
              </span>
          </button>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                      <a class="nav-link" href="/Url/Index">Link Page <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="/Url/QRCode">QR Kod</a>
                  </li>
                  
              </ul>
          </div>
          <!-- toggle switch for light and dark theme -->
          <div class="mobile-position">
              <nav class="navigation">
                  <div class="theme-switch-wrapper">
                      <label class="theme-switch" for="checkbox">
                          <input type="checkbox" id="checkbox">
                          <div class="mode-container">
                              <i class="gg-sun"></i>
                              <i class="gg-moon"></i>
                          </div>
                      </label>
                  </div>
              </nav>
          </div>
          <!-- //toggle switch for light and dark theme -->
      </nav>
  </div>
</header>
<!-- //header -->
<!-- banner -->
<section class="banner w3pvt-banner" id="home">
    <div class="container py-5">
        <div class="banner-text py-md-4">
            <div class="row banner-info">
                <div class="w3pvt-logo align-self">
                    
                   
                    @RenderBody()
                    
                </div>
                
            </div>
        </div>
    </div>
</section>




  <script src="~/web/assets/js/theme-change.js"></script><!-- theme switch js (light and dark)-->

  <script src="~/web/assets/js/jquery-3.3.1.min.js"></script><!-- default jQuery -->

<!-- magnific popup -->
<script src="~/web/assets/js/jquery.magnific-popup.min.js"></script>
<script>
  $(document).ready(function () {
    $('.popup-with-zoom-anim').magnificPopup({
      type: 'inline',

      fixedContentPos: false,
      fixedBgPos: true,

      overflowY: 'auto',

      closeBtnInside: true,
      preloader: false,

      midClick: true,
      removalDelay: 300,
      mainClass: 'my-mfp-zoom-in'
    });

    $('.popup-with-move-anim').magnificPopup({
      type: 'inline',

      fixedContentPos: false,
      fixedBgPos: true,

      overflowY: 'auto',

      closeBtnInside: true,
      preloader: false,

      midClick: true,
      removalDelay: 300,
      mainClass: 'my-mfp-slide-bottom'
    });
  });
</script>
<!-- magnific popup -->


<script src="~/web/assets/js/owl.carousel.js"></script>
<!-- script for tesimonials carousel slider -->
<script>
  $(document).ready(function () {
    $("#owl-demo1").owlCarousel({
      loop: true,
      margin: 0,
      nav: false,
      responsiveClass: true,
      responsive: {
        0: {
          items: 2,
          nav: false
        },
        736: {
          items: 3,
          nav: false
        },
        1000: {
          items: 4,
          nav: false,
          loop: false
        }
      }
    })
  })
</script>
<!-- //script for tesimonials carousel slider -->

  <!-- stats number counter-->
  <script src="~/web/assets/js/jquery.waypoints.min.js"></script>
  <script src="~/web/assets/js/jquery.countup.js"></script>
  <script>
    $('.counter').countUp();
  </script>
  <!-- //stats number counter -->

  <!-- disable body scroll which navbar is in active -->
  <script>
    $(function () {
      $('.navbar-toggler').click(function () {
        $('body').toggleClass('noscroll');
      })
    });
  </script>
  <!-- disable body scroll which navbar is in active -->

  <!--/MENU-JS-->
  <script>
    $(window).on("scroll", function () {
      var scroll = $(window).scrollTop();

      if (scroll >= 80) {
        $("#site-header").addClass("nav-fixed");
      } else {
        $("#site-header").removeClass("nav-fixed");
      }
    });

    //Main navigation Active Class Add Remove
    $(".navbar-toggler").on("click", function () {
      $("header").toggleClass("active");
    });
    $(document).on("ready", function () {
      if ($(window).width() > 991) {
        $("header").removeClass("active");
      }
      $(window).on("resize", function () {
        if ($(window).width() > 991) {
          $("header").removeClass("active");
        }
      });
    });
  </script>
  <!--//MENU-JS-->

  <!-- bootstrap js -->
  <script src="~/web/assets/js/bootstrap.min.js"></script>
  
  </body>

  </html>

Deneme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Deneme/Views/Url/Index.cshtml
@using Deneme.Models
@model List<Link>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UrlLayout.cshtml";
}

<div class="w3pvt-logo align-self">
    <h2>Indata Link İle Bağlantılarınız<br /> İçin Kısa Link Oluşturun</h2>
    <img src="~/Photo/photo.png" style="width:250px;margin-left:200px;" />
    <hr />
    <form action="#" method="post">
        <input type="text" class="form-control" name="LongUrl" placeholder="Link Giriniz..." required="" style="height:58px;">
        <button type="submit" class="btn">Link Kısalt</button>
    </form>
   
</div>
<hr />
<table class="table table-bordered" style="background-color:white;border-radius:15px;">
    <tr>

        <th>Uzun Link</th>
        <th>Kısa Link</th>
        <th>QR Kodu Üret</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.LongUrl</td>
            <td><a href="@x.LongUrl">@x.ShortUrl</a></td>
            <td><a href="/Url/QRCode/@x.Id" class="btn btn-danger" style="color:white" >QR Kodu Üret</a></td>

        </tr>
    }
</table>

@*<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title text-center" style="color:purple">QR Kod</h2>

            </div>
            <div class="modal-body">
                <div class="w3pvt-logo align-self">
                    @using (Html.BeginForm("Index", "Url", FormMethod.Post))
                    {
                        <input type="hidden" name="kod" value="@ViewBag.d" placeholder="Butona Tıklayınız..." readonly="" ; required style="width:900px;height:40px;" /><br />
                        <input type="submit" value="QR Kodu Oluştur" style="background-color:red;color:white;">


                    }

                </div>


                <br />
                @if (ViewBag.karekodImage != null)
                {
                    <img src="@ViewBag.karekodImage" alt="" style="width:400px;height:400px" />
                }
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger" data-dismiss="modal">Kapat</a>
            </div>
        </div>
    </div>
</div>*@

Deneme/Views/Url/QRCode.cshtml
@{
    ViewData["Title"] = "QRCode";
    Layout = "~/Views/Shared/UrlLayout.cshtml";
}
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
@*<div class="w3pvt-logo align-self">
    @using (Html.BeginForm("QRCode", "Url", FormMethod.Post))
    {
        <input type="text" name="kod" value="@ViewBag.d" placeholder="Butona Tıklayınız..." readonly="" ; required style="width: 900px; height: 60px; border-radius: 15px;" /><br />
        <input type="submit" value="QR Kodu Oluştur" style="background-color: #15133C; color: white; border-radius: 15px;margin-left:10px;">
        


    }

</div>*@
<div class="w3pvt-logo align-self">
    <h2>Indata Link İle Oluşturduğunuz<br /> Linkler İçin QR Kodu Üretin</h2>
    <img src="~/Photo/photo.png" style="width:250px;margin-left:200px;" />
    <hr />
    @using (Html.BeginForm("QRCode", "Url", FormMethod.Post))
    {
        <input type="text" class="form-control"name="kod" value="@ViewBag.d" placeholder="Butona Tıklayınız..." readonly="" ; required style="height:58px;">
        <button type="submit" class="btn">QR Oluştur</button>
    }

</div>


<br />
@if (ViewBag.karekodImage != null)
{
    <img src="@ViewBag.karekodImage" alt="" style="width:400px;height:400px" />
}